<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'name' => 'United States',
                'code' => 'USA',
                'dialing_code' => '+1',
                'currency' => 'USD',
                'capital' => 'Washington, D.C.',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'latitude' => 38.9072,
                'longitude' => -77.0369,
                'is_active' => true,
            ],
            [
                'name' => 'United Kingdom',
                'code' => 'GBR',
                'dialing_code' => '+44',
                'currency' => 'GBP',
                'capital' => 'London',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'latitude' => 51.5074,
                'longitude' => -0.1278,
                'is_active' => true,
            ],
            [
                'name' => 'Canada',
                'code' => 'CAN',
                'dialing_code' => '+1',
                'currency' => 'CAD',
                'capital' => 'Ottawa',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'latitude' => 45.4215,
                'longitude' => -75.6972,
                'is_active' => true,
            ],
            [
                'name' => 'Australia',
                'code' => 'AUS',
                'dialing_code' => '+61',
                'currency' => 'AUD',
                'capital' => 'Canberra',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'latitude' => -35.2809,
                'longitude' => 149.1300,
                'is_active' => true,
            ],
            [
                'name' => 'Germany',
                'code' => 'DEU',
                'dialing_code' => '+49',
                'currency' => 'EUR',
                'capital' => 'Berlin',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'latitude' => 52.5200,
                'longitude' => 13.4050,
                'is_active' => true,
            ],
            [
                'name' => 'France',
                'code' => 'FRA',
                'dialing_code' => '+33',
                'currency' => 'EUR',
                'capital' => 'Paris',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'latitude' => 48.8566,
                'longitude' => 2.3522,
                'is_active' => true,
            ],
            [
                'name' => 'Japan',
                'code' => 'JPN',
                'dialing_code' => '+81',
                'currency' => 'JPY',
                'capital' => 'Tokyo',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'latitude' => 35.6762,
                'longitude' => 139.6503,
                'is_active' => true,
            ],
            [
                'name' => 'China',
                'code' => 'CHN',
                'dialing_code' => '+86',
                'currency' => 'CNY',
                'capital' => 'Beijing',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'latitude' => 39.9042,
                'longitude' => 116.4074,
                'is_active' => true,
            ],
            [
                'name' => 'India',
                'code' => 'IND',
                'dialing_code' => '+91',
                'currency' => 'INR',
                'capital' => 'New Delhi',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'latitude' => 28.6139,
                'longitude' => 77.2090,
                'is_active' => true,
            ],
            [
                'name' => 'Brazil',
                'code' => 'BRA',
                'dialing_code' => '+55',
                'currency' => 'BRL',
                'capital' => 'Brasília',
                'region' => 'Americas',
                'subregion' => 'South America',
                'latitude' => -15.8267,
                'longitude' => -47.9218,
                'is_active' => true,
            ],
            [
                'name' => 'Mexico',
                'code' => 'MEX',
                'dialing_code' => '+52',
                'currency' => 'MXN',
                'capital' => 'Mexico City',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'latitude' => 19.4326,
                'longitude' => -99.1332,
                'is_active' => true,
            ],
            [
                'name' => 'Spain',
                'code' => 'ESP',
                'dialing_code' => '+34',
                'currency' => 'EUR',
                'capital' => 'Madrid',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'latitude' => 40.4168,
                'longitude' => -3.7038,
                'is_active' => true,
            ],
            [
                'name' => 'Italy',
                'code' => 'ITA',
                'dialing_code' => '+39',
                'currency' => 'EUR',
                'capital' => 'Rome',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'latitude' => 41.9028,
                'longitude' => 12.4964,
                'is_active' => true,
            ],
            [
                'name' => 'Netherlands',
                'code' => 'NLD',
                'dialing_code' => '+31',
                'currency' => 'EUR',
                'capital' => 'Amsterdam',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'latitude' => 52.3676,
                'longitude' => 4.9041,
                'is_active' => true,
            ],
            [
                'name' => 'Sweden',
                'code' => 'SWE',
                'dialing_code' => '+46',
                'currency' => 'SEK',
                'capital' => 'Stockholm',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'latitude' => 59.3293,
                'longitude' => 18.0686,
                'is_active' => true,
            ],
            [
                'name' => 'Norway',
                'code' => 'NOR',
                'dialing_code' => '+47',
                'currency' => 'NOK',
                'capital' => 'Oslo',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'latitude' => 59.9139,
                'longitude' => 10.7522,
                'is_active' => true,
            ],
            [
                'name' => 'Denmark',
                'code' => 'DNK',
                'dialing_code' => '+45',
                'currency' => 'DKK',
                'capital' => 'Copenhagen',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'latitude' => 55.6761,
                'longitude' => 12.5683,
                'is_active' => true,
            ],
            [
                'name' => 'Finland',
                'code' => 'FIN',
                'dialing_code' => '+358',
                'currency' => 'EUR',
                'capital' => 'Helsinki',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'latitude' => 60.1695,
                'longitude' => 24.9354,
                'is_active' => true,
            ],
            [
                'name' => 'Switzerland',
                'code' => 'CHE',
                'dialing_code' => '+41',
                'currency' => 'CHF',
                'capital' => 'Bern',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'latitude' => 46.9481,
                'longitude' => 7.4474,
                'is_active' => true,
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
